apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kuar
  name: kuar-node-port
spec:
  ports:
  - name: kuar-node-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuar
  type: NodePort
status:
  loadBalancer: {}